# W2 helpers for embedding all available Triton AOT cubin trees in one binary.
# Kept separate so the exact matrix and symbol namespace can be tested with
# `cmake -P` without enabling a compiler or CUDA.

set(VT_TRITON_AOT_AVAILABLE_ARCHES
  sm_80 sm_86 sm_89 sm_90a sm_100a sm_121a)

function(vt_triton_aot_available_arches OUT_VAR)
  set(${OUT_VAR} "${VT_TRITON_AOT_AVAILABLE_ARCHES}" PARENT_SCOPE)
endfunction()

function(vt_triton_aot_arch_tree OUT_VAR ARCH)
  set(_tree "sm_${ARCH}")
  if(_tree IN_LIST VT_TRITON_AOT_AVAILABLE_ARCHES)
    set(${OUT_VAR} "${_tree}" PARENT_SCOPE)
  else()
    set(${OUT_VAR} "" PARENT_SCOPE)
  endif()
endfunction()

function(vt_triton_aot_namespace_token OUT_VAR ARCH TOKEN)
  if(NOT ARCH MATCHES "^sm_[0-9]+a?$")
    message(FATAL_ERROR "invalid Triton AOT namespace architecture '${ARCH}'")
  endif()
  if(NOT TOKEN MATCHES "^[A-Za-z_][A-Za-z0-9_]*$")
    message(FATAL_ERROR "invalid Triton AOT namespace token '${TOKEN}'")
  endif()
  set(${OUT_VAR} "vt_aot_${ARCH}_${TOKEN}" PARENT_SCOPE)
endfunction()

# Prefix every generated external identifier containing BASE before compiling a
# vendored C launcher. This includes stable dispatchers, hash dispatchers,
# module/function globals, cubin arrays, and load/unload functions. The embedded
# kernel name string remains untouched, as required by cuModuleGetFunction.
function(vt_triton_aot_namespace_sources ARCH BASE OUTPUT_DIR OUT_VAR)
  set(_sources ${ARGN})
  if(NOT _sources)
    message(FATAL_ERROR "no Triton AOT sources to namespace for ${ARCH}/${BASE}")
  endif()
  file(MAKE_DIRECTORY "${OUTPUT_DIR}")
  set(_tokens)
  foreach(_source IN LISTS _sources)
    file(STRINGS "${_source}" _symbol_lines REGEX "${BASE}")
    string(JOIN "\n" _symbol_text ${_symbol_lines})
    string(REGEX MATCHALL
      "[A-Za-z_][A-Za-z0-9_]*${BASE}[A-Za-z0-9_]*"
      _prefixed_tokens "${_symbol_text}")
    string(REGEX MATCHALL "${BASE}[A-Za-z0-9_]*"
      _base_tokens "${_symbol_text}")
    list(APPEND _tokens ${_prefixed_tokens} ${_base_tokens})
  endforeach()
  list(REMOVE_DUPLICATES _tokens)
  list(SORT _tokens)
  if(NOT _tokens)
    message(FATAL_ERROR "no generated symbols found for ${ARCH}/${BASE}")
  endif()

  set(_header "${OUTPUT_DIR}/${ARCH}_${BASE}_namespace.h")
  file(WRITE "${_header}"
    "/* Generated by TritonAOTMultiArch.cmake: collision-free W2 symbols. */\n")
  foreach(_token IN LISTS _tokens)
    vt_triton_aot_namespace_token(_namespaced "${ARCH}" "${_token}")
    file(APPEND "${_header}" "#define ${_token} ${_namespaced}\n")
  endforeach()
  set_property(SOURCE ${_sources} APPEND PROPERTY
    COMPILE_OPTIONS "-include${_header}")
  set(${OUT_VAR} "${_sources}" PARENT_SCOPE)
endfunction()
