# vllm.cpp parity harness; oracle = upstream vLLM 0.26 chat SSE stream.
"""Capture golden OpenAI /v1/chat/completions SSE chunk sequences for the
ENGINE-BACKED tool-call parsers (qwen3 / seed_oss / kimi_k2), driven exactly as
vLLM 0.26's ``chat_completion_stream_generator`` drives them.

This is the SERVING layer above the parser ASSEMBLY gate
(``dump_parser_engine_assembly.py``): it reuses that harness's sandbox +
scenarios (so the per-delta ``DeltaMessage`` payloads come straight from the
pinned vLLM oracle, no GPU / model / wheel), and wraps each into the SSE chunk
sequence vLLM's generator emits — a leading role frame
(``delta={role:"assistant", content:""}``), one chunk per emitted delta (a
withheld ``None`` delta is skipped unless it is the terminal step), and the
terminal ``finish_reason`` with the ``tool_calls`` flip
(chat_completion/serving.py:607 parse_delta drive; :688-693 finish_reason).

The ENVELOPE fields (id/object/created/model/index) are structural and rendered
by the C++ serving path's own ``ChatCompletionStreamResponse`` serialization
(already gated field-for-field against vLLM in test_openai_serving); this golden
pins the parser-DERIVED delta payload + the framing cadence (which delta yields a
chunk, and the terminal finish_reason), which is what the serving dispatch swap
adds on top of the assembly gate.

Usage::

    VLLM_SOURCE=/home/mudler/_git/vllm python3 \
      tools/parity/dump_serving_chat_stream.py \
      --out tests/vllm/entrypoints/openai/test_serving_chat_stream_goldens.inc

Regenerate whenever the pin advances and re-run ``test_openai_serving_chat_stream``.
"""

import argparse
import importlib
import os
import shutil
import sys

# Reuse the assembly harness (sandbox + scenarios + emit helpers). Importing is
# side-effect-free (its main() is __main__-guarded).
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import dump_parser_engine_assembly as asm  # noqa: E402


def render_chunks(parser, deltas, incl):
    """Mirror chat_completion_stream_generator for a fixed delta stream: the
    leading role frame, one chunk per emitted delta (skip a withheld None unless
    terminal), and the terminal finish_reason with the tool_calls flip."""
    req = asm.Req(include_reasoning=incl)
    chunks = [("role", None, None)]  # (kind, DeltaMessage, finish_reason)
    tools_streamed = False
    for i, dt in enumerate(deltas):
        finished = i == len(deltas) - 1
        msg = parser.parse_delta(dt, [], req, finished=finished)
        if msg is not None and msg.tool_calls:
            tools_streamed = True
        if msg is None:
            if not finished:
                continue  # withheld: no chunk this step
            msg = None  # terminal empty delta below
        finish = None
        if finished:
            # named_tool_choice is False for these scenarios; a normal generation
            # terminates with "stop" unless a tool call streamed (serving.py:688).
            finish = "tool_calls" if tools_streamed else "stop"
        chunks.append(("delta", msg, finish))
    return chunks


def emit_tc(tc):
    return "SSTC{%d, %s, %s, %s, %s}" % (
        tc.index, asm.opt(tc.id), asm.opt(tc.type),
        asm.opt(tc.function.name if tc.function else None),
        asm.opt(tc.function.arguments if tc.function else None),
    )


def emit_delta(msg):
    if msg is None:
        return "SSDelta{std::nullopt, std::nullopt, std::nullopt, {}}"
    tcs = ", ".join(emit_tc(t) for t in (msg.tool_calls or []))
    role = asm.opt(getattr(msg, "role", None))
    return "SSDelta{%s, %s, %s, {%s}}" % (
        role, asm.opt(msg.content), asm.opt(msg.reasoning), tcs)


def emit_chunk(kind, msg, finish):
    if kind == "role":
        # role frame: delta = {role:"assistant", content:""}
        return ('SSChunk{true, SSDelta{std::optional<std::string>("assistant"), '
                'std::optional<std::string>(""), std::nullopt, {}}, std::nullopt}')
    return "SSChunk{false, %s, %s}" % (emit_delta(msg), asm.opt(finish))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", required=True)
    ap.add_argument("--vllm-source", default=os.environ.get(
        "VLLM_SOURCE", "/home/mudler/_git/vllm"))
    args = ap.parse_args()

    tmp = asm.build_sandbox(args.vllm_source)
    try:
        pe_pkg = {m: importlib.import_module("pe." + m) for m in asm.FAMILY_MODULES}

        lines = []
        lines.append("// GENERATED by tools/parity/dump_serving_chat_stream.py")
        lines.append("// Oracle: vLLM 0.26.0.dev0 @ 555967922 chat SSE stream "
                     "(engine-backed parsers).")
        lines.append("// DO NOT EDIT — regenerate from the pinned oracle.")
        lines.append("static const std::vector<SSScenario> kServingStreamGoldens = {")

        for name, cfg, thinking, incl, deltas in asm.make_scenarios():
            tok = asm.MockTok()
            parser = asm.make_parser(pe_pkg, cfg, thinking, tok)
            chunks = render_chunks(parser, deltas, incl)

            deltas_cpp = ", ".join(asm.esc(d) for d in deltas)
            chunks_cpp = ",\n      ".join(emit_chunk(*c) for c in chunks)
            lines.append("  SSScenario{")
            lines.append("    %s, %s, %s, %s," % (
                asm.esc(name), asm.esc(cfg),
                "true" if thinking else "false",
                "true" if incl else "false"))
            lines.append("    {%s}," % deltas_cpp)
            lines.append("    {\n      %s\n    }," % chunks_cpp)
            lines.append("  },")

        lines.append("};")
        open(args.out, "w").write("\n".join(lines) + "\n")
        print("wrote", args.out, "(%d scenarios)" % len(asm.make_scenarios()))
    finally:
        shutil.rmtree(tmp, ignore_errors=True)


if __name__ == "__main__":
    main()
